### ISSUE TITLE
ant task not usable due to res.zip

### ISSUE THREAD

**Issue by Vampire** [evolvedbinary/appbundler-maven-build#7] opened 2019-08-02 15:51 UTC
As described in TheInfiniteKind/appbundler#47, the code requires that in the res.zip the directories come first in the list of zip entries, but the entries for the directories of the res.zip you released to Maven Central come last which makes the code and thus the Ant task fail.

Can you please as a quick fix release a version where the res.zip is packed like the ant task expects it to? :-)

**Comment by adamretter** [comment] 2019-08-03 11:05
We will be happy to do a new release when this fix for the problem is merged upstream - https://github.com/TheInfiniteKind/appbundler/pull/48

**Comment by Vampire** [comment] 2019-08-05 15:39
The fix is merged upstream, but maybe you can wait a little bit more until my TheInfiniteKind/appbundler#53 is hopefully also merged.

**Comment by adamretter** [comment] 2019-08-05 15:58
@Vampire Sure. Just let me know...

**Comment by Vampire** [comment] 2019-08-05 19:16
Aaaand go :-)

**Comment by adamretter** [comment] 2019-08-06 12:00
Done :-)

**Closed by adamretter** 2019-08-06 12:00 UTC

**Comment by Vampire** [comment] 2019-08-06 12:03
Did you promote the staging repo? I don't see it on MC yet. :-)
Btw. thanks for the high responsiveness.

**Comment by Vampire** [comment] 2019-08-06 12:06
Ah, forget it, it's just the cached search index, it is actually found if I just use 1.0.4. :-)
